apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-backend
  namespace: ai-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ai-backend

  template:
    metadata:
      labels:
        app: ai-backend

    spec:
      containers:
      - name: ai-backend
        image: ai-backend:v1

        imagePullPolicy: Never

        ports:
        - containerPort: 8000